name: wifi_iot
description: Flutter plugin which can handle WiFi connections and hotspot (AP, STA)
version: 0.2.1
homepage: https://github.com/alternadom/WiFiFlutter

flutter:
  plugin:
    androidX: true
    platforms:
      android:
        package: com.alternadom.wifiiot
        pluginClass: WifiIotPlugin
      ios:
        pluginClass: WifiIotPlugin

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
